spring:
  application:
    name: my-util
#  profiles:
#    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/mytest?characterEncoding=utf8&useSSL=false&autoReconnect=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-init-sql: set names utf8mb4
      maximum-pool-size: 20

server:
  port: 8888
